// Executable scenarios for features/audio_files.feature: decoding audio files
// and the decoded-asset store (plan F-B). Every file read here was generated by
// blokkily_make_audio_fixtures from audio_fixture_content.hpp, so each sample
// is compared with the value that was written, not with a second decode.

#include "blokkily/audio/audio_asset.hpp"
#include "blokkily/audio/audio_file.hpp"

#include "fixtures/audio_fixture_content.hpp"
#include "support/audio_probe.hpp"
#include "support/process_id.hpp"

#include <cmath>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <span>
#include <string>

using namespace blokkily;
namespace fx = blokkily::audio_fixtures;

namespace {

int failures = 0;

void check(bool condition, const std::string& what) {
    if (condition) return;
    std::cerr << "FAILED: " << what << '\n';
    ++failures;
}

const std::filesystem::path fixtures = BLOKKILY_AUDIO_FIXTURES;

std::optional<DecodedAudio> decode(const char* name) {
    std::string error;
    auto decoded = decode_audio_file(fixtures / name, &error);
    if (!decoded) std::cerr << "decode " << name << " failed: " << error << '\n';
    return decoded;
}

double db(double ratio) { return 20.0 * std::log10(ratio); }

// The first frame at or above `level`: where a rising step crosses it.
std::size_t crossing(std::span<const float> samples, float level) {
    for (std::size_t frame = 0; frame < samples.size(); ++frame) {
        if (samples[frame] >= level) return frame;
    }
    return samples.size();
}

void expect_refused(const char* name) {
    std::string error;
    const auto decoded = decode_audio_file(fixtures / name, &error);
    check(!decoded.has_value(), std::string(name) + " is refused");
    check(!error.empty(), std::string(name) + " is refused with a reason");
    std::cout << "  " << name << ": " << error << '\n';
}

} // namespace

int main() {
    // Scenario: A 16-bit WAV decodes bit for bit.
    if (const auto audio = decode("sine1k_44k1_pcm16.wav")) {
        check(audio->info == AudioFileInfo{fx::sine1k_frames, fx::sine1k_rate, 1}, "PCM16 header");
        check(audio->left.size() == fx::sine1k_frames && audio->right.empty(), "PCM16 is mono");
        std::size_t wrong = 0;
        for (std::uint64_t frame = 0; frame < audio->left.size(); ++frame) {
            if (audio->left[frame] != static_cast<float>(fx::sine1k(frame)) / 32768.0F) ++wrong;
        }
        check(wrong == 0, "PCM16 samples are bit-exact (" + std::to_string(wrong) + " differ)");
        check(!audio->loop && !audio->root_key, "a file without sampler metadata has no loop or key");
    } else {
        check(false, "PCM16 decodes");
    }

    // Scenario: A 24-bit stereo WAV decodes bit for bit, channel by channel.
    if (const auto audio = decode("stereo_48k_pcm24.wav")) {
        check(audio->info == AudioFileInfo{fx::stereo24_frames, fx::stereo24_rate, 2}, "PCM24 header");
        std::size_t wrong = 0;
        for (std::uint64_t frame = 0; frame < fx::stereo24_frames; ++frame) {
            if (audio->left[frame] != static_cast<float>(fx::stereo24(frame, 0)) / 8388608.0F) ++wrong;
            if (audio->right[frame] != static_cast<float>(fx::stereo24(frame, 1)) / 8388608.0F) ++wrong;
        }
        check(wrong == 0, "PCM24 samples are bit-exact (" + std::to_string(wrong) + " differ)");
    } else {
        check(false, "PCM24 decodes");
    }

    // Scenario: A float WAV, plain or WAVE_FORMAT_EXTENSIBLE, decodes exactly.
    if (const auto audio = decode("extensible_float_48k_stereo.wav")) {
        check(audio->info == AudioFileInfo{fx::extensible_frames, fx::extensible_rate, 2},
              "EXTENSIBLE header");
        std::size_t wrong = 0;
        for (std::uint64_t frame = 0; frame < fx::extensible_frames; ++frame) {
            if (audio->left[frame] != fx::extensible(frame, 0)) ++wrong;
            if (audio->right[frame] != fx::extensible(frame, 1)) ++wrong;
        }
        check(wrong == 0, "EXTENSIBLE float samples are exact (" + std::to_string(wrong) + " differ)");
    } else {
        check(false, "EXTENSIBLE float decodes");
    }
    if (const auto audio = decode("step_44k1_float.wav")) {
        std::size_t wrong = 0;
        for (std::uint64_t frame = 0; frame < fx::step_frames; ++frame) {
            if (audio->left[frame] != fx::step(frame)) ++wrong;
        }
        check(audio->left.size() == fx::step_frames && wrong == 0, "float step file is exact");
    } else {
        check(false, "float WAV decodes");
    }
    if (const auto audio = decode("hits8_48k_pcm16.wav")) {
        std::size_t wrong = 0;
        for (std::uint64_t frame = 0; frame < fx::hits8_frames; ++frame) {
            if (audio->left[frame] != static_cast<float>(fx::hits8(frame)) / 32768.0F) ++wrong;
        }
        check(wrong == 0, "hits8 is bit-exact");
    } else {
        check(false, "hits8 decodes");
    }

    // Scenario: FLAC and AIFF decode to within one least significant bit.
    if (const auto audio = decode("sine1k_44k1.flac")) {
        check(audio->info == AudioFileInfo{fx::sine1k_frames, fx::sine1k_rate, 1}, "FLAC header");
        double worst = 0.0;
        for (std::uint64_t frame = 0; frame < fx::sine1k_frames; ++frame) {
            worst = std::max(worst, std::abs(static_cast<double>(audio->left[frame]) -
                                             fx::sine1k(frame) / 32768.0));
        }
        check(worst <= 1.0 / 32768.0, "FLAC within 1 LSB (worst " + std::to_string(worst * 32768) + " LSB)");
    } else {
        check(false, "FLAC decodes");
    }
    if (const auto audio = decode("sine1k_44k1_stereo.aiff")) {
        check(audio->info == AudioFileInfo{fx::sine1k_frames, fx::sine1k_rate, 2}, "AIFF header");
        double worst = 0.0;
        for (std::uint64_t frame = 0; frame < fx::sine1k_frames; ++frame) {
            const double expected = fx::sine1k(frame) / 32768.0;
            worst = std::max(worst, std::abs(audio->left[frame] - expected));
            worst = std::max(worst, std::abs(audio->right[frame] + expected));
        }
        check(worst <= 1.0 / 32768.0, "AIFF within 1 LSB (worst " + std::to_string(worst * 32768) + " LSB)");
    } else {
        check(false, "AIFF decodes");
    }

    // Scenario: A sample's loop and root key are read from its smpl chunk.
    if (const auto audio = decode("smpl_loop_44k1_pcm16.wav")) {
        check(audio->root_key == fx::smpl_root_key, "smpl root key is 57");
        check(audio->loop.has_value(), "smpl loop is read");
        if (audio->loop) {
            // The chunk's end frame is inclusive; LoopPoints::end is one past it.
            check(audio->loop->start == fx::smpl_loop_first, "loop starts at frame 1000, got " +
                                                                 std::to_string(audio->loop->start));
            check(audio->loop->end == fx::smpl_loop_last + 1U, "loop ends after frame 2999, got " +
                                                                   std::to_string(audio->loop->end));
        }
        check(audio->left.size() == fx::smpl_frames, "smpl file keeps all its frames");
    } else {
        check(false, "smpl WAV decodes");
    }

    // Scenario: A header can be read without decoding the file.
    {
        std::string error;
        const auto info = probe_audio_file(fixtures / "stereo_48k_pcm24.wav", &error);
        check(info == AudioFileInfo{fx::stereo24_frames, fx::stereo24_rate, 2}, "probe reads the header");
    }

    // Scenario: Broken files are refused with a reason.
    for (const char* name : {"garbage.wav", "truncated_header.wav", "truncated_data.wav", "truncated_data.aiff",
                             "empty.wav",
                             "no-such-file.wav"}) {
        expect_refused(name);
    }
    {
        std::string error;
        check(!probe_audio_file(fixtures / "garbage.wav", &error) && !error.empty(),
              "probe refuses garbage with a reason");
    }

    // Scenario: A 44.1 kHz file resampled to 48 kHz keeps its pitch, level and timing.
    if (const auto audio = decode("sine1k_44k1_pcm16.wav")) {
        const double ratio = 48000.0 / 44100.0;
        const auto output = resample(audio->left, ratio);
        check(output.size() == 48000, "44.1k->48k gives 48000 frames, got " + std::to_string(output.size()));
        const auto middle = std::span<const float>(output).subspan(4800, 38400);
        const double frequency = probe::dominant_frequency(middle, 48000.0, 990.0, 1010.0, 0.25);
        check(std::abs(frequency - 1000.0) <= 1.0, "resampled tone is 1 kHz +-1 Hz, got " +
                                                       std::to_string(frequency));
        const auto source_middle = std::span<const float>(audio->left).subspan(4410, 35280);
        const double level = db(probe::rms(middle) / probe::rms(source_middle));
        check(std::abs(level) <= 0.1, "resampled RMS within 0.1 dB, off by " + std::to_string(level));
        check(resample(audio->left, ratio) == output, "resampling is deterministic");
    }
    if (const auto audio = decode("step_44k1_float.wav")) {
        const auto output = resample(audio->left, 48000.0 / 44100.0);
        const std::size_t at = crossing(output, 0.25F);
        const auto expected = static_cast<long>(fx::step_frame * 48000 / 44100);
        check(std::labs(static_cast<long>(at) - expected) <= 2,
              "step marker at frame " + std::to_string(at) + ", expected " + std::to_string(expected) + " +-2");
    }
    check(resample({}, 2.0).empty() && resample(std::vector<float>(10, 1.0F), 0.0).empty(),
          "resampling nothing, or by a non-positive ratio, gives nothing");

    // Scenario: A file already decoded is not decoded again.
    {
        AudioAssetCache cache;
        std::string error;
        const auto sine = fixtures / "sine1k_44k1_pcm16.wav";
        const auto first = cache.load(sine, 48000.0, std::nullopt, &error);
        check(first != nullptr, "cache loads at the engine rate: " + error);
        const auto again = cache.load(fixtures / "." / "sine1k_44k1_pcm16.wav", 48000.0, std::nullopt, &error);
        check(again == first, "a second load returns the same asset");
        check(cache.decode_count() == 1, "a cache hit does not decode again, decodes: " +
                                             std::to_string(cache.decode_count()));
        if (first) {
            check(first->rate == 48000 && first->frames == 48000 && first->left.size() == 48000 &&
                      first->right.empty(),
                  "an asset at the engine rate is resampled to it");
            check(first->peaks.size() == (48000 + audio_peak_block - 1) / audio_peak_block,
                  "one peak pair per 256 frames");
        }

        const auto native = cache.load(sine, 0.0, std::nullopt, &error);
        check(native && native->rate == fx::sine1k_rate && native->frames == fx::sine1k_frames,
              "target rate 0 keeps the file's own rate");
        check(cache.load(sine, 44100.0, std::nullopt, &error) == native,
              "asking for the native rate by number is the same asset");
        check(cache.decode_count() == 2, "each distinct rate decodes once");

        // Scenario: A file that no longer matches the project is missing, not played wrong.
        const AudioFileInfo right_info{fx::sine1k_frames, fx::sine1k_rate, 1};
        check(cache.load(sine, 48000.0, right_info, &error) == first, "a matching expectation is a hit");
        error.clear();
        const auto mismatch = cache.load(sine, 48000.0, AudioFileInfo{fx::sine1k_frames + 1, fx::sine1k_rate, 1}, &error);
        check(mismatch == nullptr, "an expectation mismatch on a cached file is refused");
        check(error.find("missing") != std::string::npos, "the mismatch is reported as missing: " + error);
        error.clear();
        const auto fresh_mismatch = cache.load(fixtures / "stereo_48k_pcm24.wav", 0.0,
                                               AudioFileInfo{fx::stereo24_frames, 44100, 2}, &error);
        check(fresh_mismatch == nullptr && error.find("missing") != std::string::npos,
              "a rate mismatch on an uncached file is reported as missing: " + error);
        check(cache.decode_count() == 2, "a mismatched file is refused from its header, without decoding");
        check(cache.load(fixtures / "no-such-file.wav", 48000.0, right_info, &error) == nullptr && !error.empty(),
              "a file that is gone is missing");

        // Stereo, and loop points, follow the rate.
        auto stereo = cache.load(fixtures / "stereo_48k_pcm24.wav", 44100.0, std::nullopt, &error);
        check(stereo && stereo->frames == 4410 && stereo->right.size() == 4410,
              "a stereo asset resamples both channels");
        const auto looped = cache.load(fixtures / "smpl_loop_44k1_pcm16.wav", 48000.0, std::nullopt, &error);
        check(looped && looped->loop == LoopPoints{1088, 3265} && looped->root_key == 57,
              "loop points scale with the rate and the root key is kept");

        // Scenario: Only assets still in use survive a purge.
        const std::size_t held = cache.size();
        const std::uint64_t decodes = cache.decode_count();
        check(held == 4, "four assets are cached, got " + std::to_string(held));
        cache.purge_unused();
        check(cache.size() == held, "purging keeps every asset something still holds");
        const std::weak_ptr<const AudioAsset> watch = stereo;
        stereo.reset();   // now only the cache holds it
        cache.purge_unused();
        check(watch.expired() && cache.size() == held - 1, "an asset nothing holds is purged");
        check(cache.load(sine, 48000.0, std::nullopt, &error) == first && cache.decode_count() == decodes,
              "a held asset stays cached across a purge");
    }

    // Scenario: A recorded take is registered without reading its file.
    {
        AudioAssetCache cache;
        std::string error;
        AudioAsset take;
        take.rate = 48000;
        take.left = {0.0F, 0.5F, -0.25F};
        take.right = {0.0F, -0.5F, 0.75F};
        const auto path =
            std::filesystem::temp_directory_path() /
            ("blokkily-take-" + std::to_string(blokkily::test::process_id()) + ".wav");
        cache.insert(path, take);
        const auto loaded = cache.load(path, 48000.0, AudioFileInfo{3, 48000, 2}, &error);
        check(loaded && loaded->frames == 3 && loaded->right[2] == 0.75F, "an inserted take is found: " + error);
        check(loaded && loaded->peaks.size() == 1 && loaded->peaks[0] == std::pair{-0.5F, 0.75F},
              "an inserted take gets its peaks");
        check(cache.decode_count() == 0, "an inserted take is never decoded");
    }

    // Scenario: A file changed on disk is decoded again.
    {
        const auto dir = std::filesystem::temp_directory_path() /
                         ("blokkily-assets-" + std::to_string(blokkily::test::process_id()));
        std::filesystem::create_directories(dir);
        const auto copy = dir / "changing.wav";
        std::filesystem::copy_file(fixtures / "sine1k_44k1_pcm16.wav", copy,
                                   std::filesystem::copy_options::overwrite_existing);
        AudioAssetCache cache;
        std::string error;
        const auto before = cache.load(copy, 0.0, std::nullopt, &error);
        std::filesystem::copy_file(fixtures / "hits8_48k_pcm16.wav", copy,
                                   std::filesystem::copy_options::overwrite_existing);
        const auto after = cache.load(copy, 0.0, std::nullopt, &error);
        check(before && after && after != before && after->rate == fx::hits8_rate &&
                  cache.decode_count() == 2,
              "a replaced file is decoded again");
        std::filesystem::remove_all(dir);
    }

    if (failures != 0) {
        std::cerr << failures << " audio asset check(s) failed\n";
        return 1;
    }
    std::cout << "audio asset checks passed\n";
    return 0;
}
