Feature: Audio files decode into the samples they hold
  Audio clips and the sampler play files the producer brings in. Every file is
  decoded once, into exactly the samples it holds, at the rate it is played at,
  and a file that is broken or no longer the one the project names is refused
  rather than played wrong. Executable: tests/audio_assets_tests.cpp (CTest
  audio_assets), on files generated by blokkily_make_audio_fixtures.

  Scenario: A 16-bit WAV decodes bit for bit
    Given a mono 16-bit WAV of a 1 kHz sine at 44.1 kHz
    When it is decoded
    Then every sample equals the written integer divided by full scale
    And the header reports its frames, rate and one channel

  Scenario: A 24-bit stereo WAV decodes bit for bit, channel by channel
    Given a stereo 24-bit WAV with a different tone on each channel
    When it is decoded
    Then both channels hold exactly the written samples

  Scenario: A float WAV, plain or WAVE_FORMAT_EXTENSIBLE, decodes exactly
    Given a stereo float WAV written with the EXTENSIBLE header, and a plain float WAV
    When they are decoded
    Then every sample equals the written float

  Scenario: FLAC and AIFF decode to within one least significant bit
    Given the 1 kHz sine saved as 16-bit FLAC, and as stereo 16-bit AIFF
    When they are decoded
    Then no sample differs from the written value by more than one 16-bit step

  Scenario: A sample's loop and root key are read from its smpl chunk
    Given a WAV whose smpl chunk names MIDI note 57 and a loop over frames 1000 to 2999
    When it is decoded
    Then its root key is 57
    And its loop starts at frame 1000 and ends after frame 2999

  Scenario: A header can be read without decoding the file
    Given a stereo 24-bit WAV
    When it is probed
    Then its frames, rate and channel count are reported

  Scenario: Broken files are refused with a reason
    Given garbage bytes, a WAV cut off inside its header, a WAV and an AIFF cut off inside their audio, an empty file and a missing file
    When each is decoded
    Then each is refused with a reason
    And none is returned as a shorter file

  Scenario: A 44.1 kHz file resampled to 48 kHz keeps its pitch, level and timing
    Given one second of 1 kHz at 44.1 kHz, and a DC step at 44.1 kHz frame 22050
    When they are resampled to 48 kHz
    Then the result has exactly 48000 frames
    And the tone is 1 kHz within 1 Hz, and its RMS level is within 0.1 dB
    And the step lands on 48 kHz frame 24000 within two frames

  Scenario: A file already decoded is not decoded again
    Given a file loaded into the asset store at the engine rate
    When it is loaded again at the same rate
    Then the same decoded audio comes back and the file was decoded only once

  Scenario: A file that no longer matches the project is missing, not played wrong
    Given the project expects a file with other frames, rate or channels than the file has
    When the file is loaded
    Then it is reported as missing, without decoding it

  Scenario: Only assets still in use survive a purge
    Given decoded files, one of which nothing plays any more
    When unused assets are purged
    Then only the one nothing holds is dropped

  Scenario: A recorded take is registered without reading its file
    Given a take recorded into memory
    When it is registered under its file name and then loaded
    Then it comes back with its peaks, and no file was decoded

  Scenario: A file changed on disk is decoded again
    Given a file already in the asset store
    When the file is replaced on disk
    Then loading it decodes the new contents
