Feature: A sampler plays recorded sound as an instrument
  The built-in sampler plays a program of zones: keyed zones that follow the
  pitch of the key, and drum kits with one sample per key or a loop chopped
  into slices on consecutive keys. These scenarios cover its sound engine
  (item 1.9) and are proved from audio rendered by SamplerInstrument::process
  on files generated by blokkily_make_audio_fixtures. Each is its own CTest
  test, named in the comment above it (blokkily_sampler_tests <case>, or
  blokkily_realtime_checks). The scenarios after those cover the sampler in
  the application (item 2.3): the factory and browser, a program edited while
  the song plays, its panel, undo, save and load, and the bounce. They are
  proved by blokkily_sampler_app_tests <case> through the production
  SongEngine and render callback, and by the bdd_sampler gate, which drives
  the real application and names each step it reaches.

  # sampler_file_metadata
  Scenario: A sample brings its own root key and loop
    Given a WAV whose smpl chunk names note 57 and a sustain loop
    When the producer makes a zone from it
    Then the zone's root key is 57 and its loop is the file's loop
    And note 57 sounds 440 Hz and still sounds after three times the file's length

  # sampler_missing_sample
  Scenario: A missing sample is reported, not fatal
    Given a program whose zones point at a missing file, a broken file and a good file
    When the program is loaded
    Then both broken zones are reported with their paths and stay in the program
    And their keys are silent while the good zone still plays

  # sampler_keyed_pitch
  Scenario: A loaded sample plays at the pitch of the key
    Given a keyed zone tuned so that its 44.1 kHz file sounds A4 on key 69
    When the producer plays A5
    Then the rendered audio is at 880 Hz
    When they play A4 retuned by +50 cents
    Then the rendered audio is at 452.9 Hz
    And a degree of 19-EDO sounds at the frequency the tuning gives it

  # sampler_key_velocity_range
  Scenario: Keys and velocities outside a zone are silent
    Given a zone mapped from C3 to C5
    When a note below C3 or above C5 is played
    Then the track renders silence
    And two velocity layers on one key play different samples for a soft and a hard note

  # sampler_velocity
  Scenario: Velocity sets the level
    When the same note is played at full and at half velocity
    Then the full-velocity note is twice as loud

  # sampler_envelope
  Scenario: The envelope shapes the note
    Given a zone with a 10 ms attack, a 20 ms decay to half, and a 50 ms release
    When a key is held and let go
    Then the audio reaches full level after 10 ms, holds at half, and is silent 60 ms after release
    And one note-off releases two voices stacked on the same key

  # sampler_loop
  Scenario: A looped sample sustains while the key is held
    Given a short sample with a forward loop, and the same with a ping-pong loop
    When a key is held for three times the sample's length
    Then the track is still sounding and the loop seam adds no jump
    And with the loop off the note ends with the sample

  # sampler_loop_seam (regression)
  Scenario: A loop seam reads the loop, not what comes before it
    Given a sample whose frames before the forward loop are nothing like the loop's end
    When a key a semitone above the root is held for four turns of the loop
    Then every turn of the loop is as smooth as the sine it loops
    And after the first turn it sounds sample for sample like the same loop without that lead-in

  # sampler_kit_slices
  Scenario: A loop is chopped into pads
    Given a loop of eight hits, each at its own pitch
    When it is chopped into 8 slices starting at C2
    Then keys C2 to G2 each play their own hit, sample for sample
    And each pad stops exactly at the end of its slice

  # sampler_one_shot_and_choke
  Scenario: One-shot pads ignore note length and choke groups cut each other
    Given a one-shot pad
    When it is let go early
    Then it plays to the end of its sample
    Given pads 42 and 46 share a choke group
    When 46 rings and 42 is struck
    Then 46 falls silent within 64 samples

  # sampler_state
  Scenario: A sampler's program is saved and reloaded exactly
    Given a sampler with two keyed zones, loops, envelopes, gain and pan
    When its state is saved and loaded into a new sampler
    Then the new sampler renders the same audio, bit for bit
    And a project holding the sampler round-trips byte for byte
    And a state of another version, or with a malformed zone, is refused and changes nothing

  # sampler_relative_paths
  Scenario: Samples inside the project folder move with it
    Given a sampler whose samples lie inside the project directory
    When its state is saved
    Then the samples are named relative to the project directory
    And the state reloads and plays from the same directory, and reports the files missing from another

  # sampler_parameters, sampler_pattern_locks
  Scenario: Parameter locks change the sampler without rewriting it
    Given a sampler playing a held note
    When a step's automation lock sets its gain and a later step's modulation lock adds to it
    Then the rendered level follows the lock and then the lock plus the modulation
    And a later value leaves the modulation as an offset, never folded into the base

  # sampler_kit_handoff
  Scenario: A new program reaches a running sampler without cutting it
    Given a sampler holding a note
    When a new program is loaded while it plays
    Then the held note keeps its old sound and the next note plays the new one
    And the old program is freed once its last note has ended

  # realtime_sampler_voices
  Scenario: The sampler plays without the render callback allocating
    Given a sampler with every voice busy, stealing, choking, taking parameters and a new program
    When it renders on its own and as a track instrument of the song engine
    Then not one process() call allocates or frees memory

  # sampler_app_factory; bdd_sampler "sampler: chosen in the browser"
  Scenario: The sampler is chosen in the browser like any other instrument
    Given the browser lists "Sampler" and "Drum Sampler" as built-in instruments
    When the producer clicks "Sampler" with a track selected
    Then the track plays a keyed sampler created by the processor factory
    And the sampler panel takes the device box's place, at least 220 px tall
    And the browser below it still shows at least two rows
    When a WAV whose smpl chunk names note 57 is loaded into it
    Then the panel shows the file, root key A3 and a forward loop
    And key 69 plays 880 Hz through the production render callback

  # sampler_app_live_swap; bdd_sampler "sampler: a root-key edit is heard without a rebuild or recompile"
  Scenario: A program edit reaches a playing sampler without stopping the song
    Given the song is playing key 69 on every beat through a sampler rooted at 57
    When the producer presses the root key's + twelve times in the panel
    Then the same engine and the same sampler play on, with no rebuild and no recompile
    And the playhead moves on by exactly each block rendered
    And the note already sounding keeps 880 Hz while the next beat plays 440 Hz

  # bdd_sampler "sampler: undo and redo reach the running sampler"
  Scenario: Undo gives a playing sampler its earlier program back
    Given the root key was stepped from 57 to 69 while the song played
    When the producer undoes once
    Then the root key reads 57 and the next beat plays 880 Hz from the same engine
    When they redo
    Then the next beat plays 440 Hz again

  # sampler_app_bounce_parity; bdd_sampler "sampler: chopped into eight pads from the panel",
  # "sampler: pad 36 plays 200 Hz on the downbeat and pad 40 1000 Hz a beat later"
  Scenario: A loop is chopped into pads from the panel
    Given a Drum Sampler holding a loop of eight tones, one every 6000 frames
    When the producer leaves SLICES at 8 and presses CHOP
    Then the kit has eight pads on C2 to G2, and the panel steps to the second, on C#2
    And a step on C2 plays 200 Hz on its downbeat and a step on E2 plays 1000 Hz a beat later

  # bdd_sampler "sampler: save, move the folder and load, samples found beside the project"
  Scenario: A session with samplers is saved, moved and loaded
    Given the pads' loop lies in a folder beside the project file
    When the session is saved, its folder is moved, and it is opened from there
    Then the loop is named relative to the project and found in the moved folder
    And the keys play 440 Hz and the pads 200 Hz and 1000 Hz, as before

  # sampler_app_bounce_parity; bdd_sampler "sampler: the bounce read back matches the render"
  Scenario: A bounce of keyed and kit samplers is what the engine plays
    Given a song with a keyed sampler and a chopped kit
    When it is bounced to a 32-bit float WAV
    Then the file read back equals the production callback's render, sample for sample
    And it holds the keys' pitches and each pad's slice at its step
