# Feature fragment: audio_assets (item 1.3, F-B audio files and decoded-asset store). See docs/plans/daw-program.md.
#
# Audio files are decoded by libsndfile and resampled by libsamplerate. Both
# are REQUIRED and PRIVATE to blokkily_core: no public header includes them,
# so nothing that links the core has to know which decoder it uses.
#
# The test audio is generated by the build: blokkily_make_audio_fixtures writes
# every file into ${BLOKKILY_AUDIO_FIXTURE_DIR}. No audio binary is checked in.

pkg_check_modules(SNDFILE REQUIRED IMPORTED_TARGET sndfile)
pkg_check_modules(SAMPLERATE REQUIRED IMPORTED_TARGET samplerate)

target_sources(blokkily_core PRIVATE
    src/audio/audio_file.cpp
    src/audio/audio_asset.cpp)
target_link_libraries(blokkily_core PRIVATE PkgConfig::SNDFILE PkgConfig::SAMPLERATE)

if(BLOKKILY_BUILD_TESTS)
    set(BLOKKILY_AUDIO_FIXTURE_DIR "${CMAKE_BINARY_DIR}/audio-fixtures")
    set(BLOKKILY_AUDIO_FIXTURE_FILES
        sine1k_44k1_pcm16.wav
        step_44k1_float.wav
        stereo_48k_pcm24.wav
        extensible_float_48k_stereo.wav
        smpl_loop_44k1_pcm16.wav
        hits8_48k_pcm16.wav
        truncated_data.wav
        truncated_header.wav
        empty.wav
        garbage.wav
        sine1k_44k1.flac
        sine1k_44k1_stereo.aiff
        truncated_data.aiff)
    list(TRANSFORM BLOKKILY_AUDIO_FIXTURE_FILES PREPEND "${BLOKKILY_AUDIO_FIXTURE_DIR}/"
         OUTPUT_VARIABLE blokkily_audio_fixture_outputs)

    # The generator writes its WAV files by hand and uses libsndfile only for
    # FLAC and AIFF, so the reader under test never checks its own writer.
    add_executable(blokkily_make_audio_fixtures tests/fixtures/make_audio_fixtures.cpp)
    target_link_libraries(blokkily_make_audio_fixtures PRIVATE PkgConfig::SNDFILE)
    target_compile_options(blokkily_make_audio_fixtures PRIVATE
        $<$<CXX_COMPILER_ID:GNU,Clang>:-Wall;-Wextra;-Wpedantic;-Werror>)
    add_custom_command(
        OUTPUT ${blokkily_audio_fixture_outputs}
        COMMAND blokkily_make_audio_fixtures "${BLOKKILY_AUDIO_FIXTURE_DIR}"
        DEPENDS blokkily_make_audio_fixtures
        COMMENT "Generating audio test fixtures"
        VERBATIM)
    add_custom_target(blokkily_audio_fixtures ALL DEPENDS ${blokkily_audio_fixture_outputs})

    add_executable(blokkily_audio_assets_tests tests/audio_assets_tests.cpp)
    target_include_directories(blokkily_audio_assets_tests PRIVATE tests)
    target_link_libraries(blokkily_audio_assets_tests PRIVATE blokkily_core)
    target_compile_definitions(blokkily_audio_assets_tests PRIVATE
        BLOKKILY_AUDIO_FIXTURES="${BLOKKILY_AUDIO_FIXTURE_DIR}")
    target_compile_options(blokkily_audio_assets_tests PRIVATE
        $<$<CXX_COMPILER_ID:GNU,Clang>:-Wall;-Wextra;-Wpedantic;-Werror>)
    add_dependencies(blokkily_audio_assets_tests blokkily_audio_fixtures)
    add_test(NAME audio_assets COMMAND blokkily_audio_assets_tests)
    set_tests_properties(audio_assets PROPERTIES
        LABELS "unit;audio;assets"
        ENVIRONMENT "${BLOKKILY_HEADLESS_TEST_ENV}"
        TIMEOUT 60)
endif()
